### ISSUE TITLE
Short fix Steam profile function in Player Edit

### ISSUE THREAD

**Issue by MkZ0ck** [Cyberbyte-Studios/CyberWorks-3#15]
Hi here I have a short fix for you guys.
Steam Profile function wont work now.

Here my fix for it...

Goto Cyberworks\resources\views\life\player.twig
Line 30 <a target="_blank" href="http://steamcommunity.com/profiles/{{ player.playerid }}"

Change to <a target="_blank" href="http://steamcommunity.com/profiles/{{ player.pid }}"

Then it works for me, I hope it will help.

Greetings

**Comment by cammygames** [comment]
Good spot. I will get that changed shortly.

**Comment by MightySCollins** [comment]
Merged in #17
