### ISSUE TITLE
Can't use docker and nginx won't install, any other way to install?

### ISSUE THREAD

**Issue by BeFreezy** [Cyberbyte-Studios/CyberWorks-3#16]
Hey,

My VPS is hosted on a kernel version that is not supported by docker, and I can't get the nginx stuff to work, so I'm asking this, is there a bundled version which is already setup where I only have to fill in my database information? Would love to use cyberworks.

**Comment by BeFreezy** [comment]
got nginx to work afterall.
*CLOSE*

**Comment by BeFreezy** [comment]
well nvm, can't use the code to replace in my server block.

`nginx: [emerg] host not found in upstream "php"`

**Comment by MightySCollins** [comment]
You also have an option of Apache. I am writing a guide for that now.
