### ISSUE TITLE
DataTable error

### ISSUE THREAD

**Issue by xTimoDEx** [Cyberbyte-Studios/CyberWorks-3#22]
DataTables warning: table id=datatable - Ajax error. For more information about this error, please see http://datatables.net/tn/7

**Comment by cammygames** [comment]
Please can you re submit this issue following the issue template https://github.com/Cyberbyte-Studios/CyberWorks-3/blob/master/ISSUE_TEMPLATE.MD Thanks.

**Comment by MightySCollins** [comment]
Have you manages to fix this?
