### ISSUE TITLE
no way to change own password

### ISSUE THREAD

**Issue by BeFreezy** [Cyberbyte-Studios/CyberWorks-3#32]
* **I'm submitting a ... **
  - [x] bug report
  - [ ] feature request
  - [ ] support request

Please only submit the section relevant to what you are submitting.

**Bug Report**

* **What is the current behavior?**

No way of changing my own own password

* **What is the expected behavior?**

some way to change it yourself

* **Steps to reproduce?**
/
* **Please tell us about your environment:**

Apache2 Server, nothing special.

* **Checklist**
  - [ ] Attached Relevant Logs
  - [ ] Steps to reproduce
  - [ ] Screenshots

**Comment by cammygames** [comment]
You can edit users passwords via the users area. For user to change their own passwords without access to this section we have password resets which where mentioned in the installer.

`
In order for password resets to work you need to setup an email address for the password reset email to be sent from. I suggest you setup an email just for this purpose.
If valid details are not provided then password resets will NOT work!
`[HERE](https://github.com/Cyberbyte-Studios/CyberWorks-3/blob/master/resources/views/installView.php#L62)
