### ISSUE TITLE
slim application error

### ISSUE THREAD

**Issue by BeFreezy** [Cyberbyte-Studios/CyberWorks-3#34]
* **I'm submitting a ... **
  - [x] bug report
  - [ ] feature request
  - [ ] support request

Please only submit the section relevant to what you are submitting.

Bug Report
------
* **What is the current behavior?**
not letting me reset my password
* **What is the expected behavior?**
redierect me to the passwor reset page

* **Please tell us about your environment:**
apache2 server
* **Checklist**
  - [x] Attached Relevant Logs
  - [ ] Steps to reproduce
  - [ ] Screenshots

[error.log](https://github.com/Cyberbyte-Studios/CyberWorks-3/files/1727983/error.log)

**Comment by BeFreezy** [comment]
got another one on the register page, logs also attached.

[error.log](https://github.com/Cyberbyte-Studios/CyberWorks-3/files/1728469/error.log)

**Comment by cammygames** [comment]
Register page was removed in favour of admins adding users then self for security.

**Comment by BeFreezy** [comment]
alright, I'll just remove the register link then, thanks.
