### ISSUE TITLE
Database Error //Support Request//

### ISSUE THREAD

**Issue by JimBob0121** [Cyberbyte-Studios/CyberWorks-3#41]
Support Request
------

* **Details of your issue?**
Having issues regarding sql with the panel

* **Please tell us about your environment:**

* **Checklist**
  - [ ] Attached Relevant Logs
https://hastebin.com/vivopeneye.tex
the sql i'm using
https://hastebin.com/olesazoteq.sql
  - [ ] Screenshots

* **Other information**

**Comment by cammygames** [comment]
CyberWorks 3 Currently Only Supports the version of the database where pid is used throughout to store the players steam id.

**Comment by JimBob0121** [comment]
Will their ever be something to support others in the future?

**Comment by MightySCollins** [comment]
Probally not for now. The changes might be possible for you to do yourself though by finding and replacing.
