### ISSUE TITLE
Only variables should be passed by reference

### ISSUE THREAD

**Issue by JuanAdamuz** [Cyberbyte-Studios/CyberWorks-3#43]
Notice: Only variables should be passed by reference in /home/forge/panel.poplife.wtf/public/installer.php on line 182

Notice: Only variables should be passed by reference in /home/forge/panel.poplife.wtf/public/installer.php on line 183

Just after installing

**Comment by MightySCollins** [comment]
Thanks for reporting this, looks like it might be a code issue. Can I just confirm the PHP version you are using?
