### ISSUE TITLE
'View Containers' permission cannot be set to true.

### ISSUE THREAD

**Issue by thedarthonian** [Cyberbyte-Studios/CyberWorks-3#54]
* **I'm submitting a ...**
  - [x] bug report

Please only submit the section relevant to what you are submitting.

Bug Report
------
* **What is the current behaviour?**
If you set view container permission to true, then save, it immediately reverts to false.

* **What is the expected behaviour?**
It will stay as true

* **Steps to reproduce?**
    1. Just attempt to set View Container to true on a group, and it will go back to false.

* **Please tell us about your environment:**
Web-Hosted

* **Checklist**
  - [ ] Attached Relevant Logs
  - [ ] Steps to reproduce
  - [ ] Screenshots

* **Other information**

**Comment by cammygames** [comment]
Will Investigate

**Comment by C0kkie** [comment]
Added a fix for it. Maybe you will merge it

**Comment by C0kkie** [comment]
Think you can close this^^
