### ISSUE TITLE
Ability to add more white listing boxes

### ISSUE THREAD

**Issue by MrDexter** [Cyberbyte-Studios/CyberWorks-3#58]
* **I'm submitting a ... **
  - [ ] feature request

* **What would you like to see added / changed?**
So I have Departments within the police for Example the flight Departmemt
They have white listing just like the Cop level so the ability to white list them on the site would be great.

Alternatively you could have A Police section to white list to police and then the departments and then the same for medics.

**Comment by cammygames** [comment]
Unfortuantly this would have to be something you added your self as it would be specific to your setup.
