### ISSUE TITLE
Users don't have the permissions set to them

### ISSUE THREAD

**Issue by thedarthonian** [Cyberbyte-Studios/CyberWorks-3#59]
* **I'm submitting a ... **
  - [ ] bug report

Please only submit the section relevant to what you are submitting.

Bug Report
------
* **What is the current behavior?** 
Setting these permissions: http://prntscr.com/iqsoxr

Only let a user see this: http://prntscr.com/iqsp3a

* **What is the expected behavior?**

The given permissions will allow users to see the panels on the left and access the pages.

* **Steps to reproduce?**
    1. Set a group with the above permissions and apply it to a user, then login through the user account.

* **Please tell us about your environment:**
Web-Hosted (Hostinger)

**Comment by cammygames** [comment]
Are you using the latest 1.1.3

**Comment by thedarthonian** [comment]
@cammygames Yep

**Comment by cammygames** [comment]
Ok i will investigate but im sure this issue was fixed in 1.1.3

**Comment by thedarthonian** [comment]
@cammygames I'll reinstall the 1.13 version, it may have just been a failed file or sth stupid like that.

**Comment by thedarthonian** [comment]
@cammygames Re-installed 1.13 and it's working fine now.

**Comment by cammygames** [comment]
Ok glad you were able to resolve your issue.
