### ISSUE TITLE
Slim Application Error

### ISSUE THREAD

**Issue by BenjiBoyyy** [Cyberbyte-Studios/CyberWorks-3#71]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [X] support request

Please only submit the section relevant to what you are submitting.

Bug Report
------
* **What is the current behavior?**
When I log into the panel I get a slim application error.
* **What is the expected behavior?**
To log into the panel
* **Steps to reproduce?**
    1. Install the panel with database info
    2. Delete installer.php and refresh 
    3. Try to log in to using details used on installation page [Screenshot](https://i.imgur.com/qZfwTfw.png)

* **CyberWorks 3 Version:** 1.1.4

* **Please tell us about your environment:**
Being run on a windows vm with xampp
* **Checklist**
  - [ ] Attached Relevant Logs
  - [X] Steps to reproduce
  - [X] Screenshots

* **Other information**
No logs are being written to the logs folder also

**Comment by MightySCollins** [comment]
Still have this issue?

**Comment by C0kkie** [comment]
Looks like this can be closed
