### ISSUE TITLE
DataTables warning

### ISSUE THREAD

**Issue by JapE1337** [Cyberbyte-Studios/CyberWorks-3#77]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

Please only submit the section relevant to what you are submitting.

Bug Report
------
* **What is the current behavior?**

* **What is the expected behavior?**

* **Steps to reproduce?**
    1. Install clean version.
    2. Sign in.
    3. Go to either the "Vehicles" or "Players" site. 

* **CyberWorks 3 Version:**
0.5.3

* **Please tell us about your environment:**
OVH Windows Server 2012 (Located in FR)
Apache 2.4.33
PHP 7.2.5
MariaDB 15.1

* **Checklist**
  - [x] Attached Relevant Logs
  - [x] Steps to reproduce
  - [x] Screenshots

* **Other information**

Sceenshot: https://gyazo.com/e2f291c8e52396aace11b8e2b0cd79e7

**Comment by JapE1337** [comment]
I ended up downgrading to an older version of cyberworks, and that work's great. I don't know if it's because i'm using altislife 4, and not 5?

**Comment by MightySCollins** [comment]
Yep that's probably the problem we only support 5
