### ISSUE TITLE
Slim Application Error

### ISSUE THREAD

**Issue by KazeroG** [Cyberbyte-Studios/CyberWorks-3#9]
A website error has occurred. Sorry for the temporary inconvenience.

Ps: i change the port to :8084 because already in use by apache !

CPU:
2 vCore

RAM:
8324 Mo

Stockage:
50 Go SSD

OS:
Debian 8.9

**Comment by cammygames** [comment]
Could you please send over the logs and i will take a look.

**Comment by cammygames** [comment]
Closing Issue as no response within 13 days. If you are still having this issue please open an issue.
